layout: default
title: Mastermind Holberton School Challenge
text: Home
author: David Orejuela, Emma Navarro, Santiago Peña, Nathaly Sotomayor
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here you found how to build a Mastermind game in a programming language.

share-links-active:
  twitter: true
  facebook: true
  linkedin: true

defaults:
  social-share: true # add social media sharing buttons to all blog post
  
  scope:
    path: "" # any file that's not a post will be a "page" layout by default
  values:
    layout: ""

# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - LICENSE
  - README.md
  - screenshot.png
  - docs/
  
# social links
github_username: emmanavarro
github_username: santiagopemo
github_username: daorejuela1 # DO NOT include the @ character, or else the build will fail!
github_username: nathsotomayor # DO NOT include the @ character, or else the build will fail!

theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
