layout: default
title: Mastermind Challenge
authors:
  david:
    name: David Orejuela
    twitter_username: DavidOrejuela14
    github_username: daorejuela1

  emma:
    name: Emma Navarro
    twitter_username: Ayy_Emma
    github_username: emmanavarro

  santiago:
    name: Santiago Peña
    twitter_username: Santiag11470161
    github_username: santiagopemo

  nathaly:
    name: Nathaly Sotomayor
    twitter_username: nathsotomayor # DO NOT include the @ character, or else the build will fail!
    github_username:  nathsotomayor # DO NOT include the @ character, or else the build will fail!
#author: David Orejuela, Emma Navarro, Santiago Peña, Nathaly Sotomayor
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Here you found how to build a Mastermind game in a programming language.
  
copyright: © 2020. All rights reserved.
permalink: pretty
  
# social links
#authors:
#  david:
#    name: David Orejuela
#    twitter_username: DavidOrejuela14
#    github_username: daorejuela1

#  emma:
#   name: Emma Navarro
#    twitter_username: Ayy_Emma
#    github_username: emmanavarro

#  santiago:
#    name: Santiago Peña
#    twitter_username: Santiag11470161
#    github_username: santiagopemo

#  nathaly:
#    name: Nathaly Sotomayor
#    twitter_username: nathsotomayor # DO NOT include the @ character, or else the build will fail!
#    github_username:  nathsotomayor # DO NOT include the @ character, or else the build will fail!

theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
